add Material class
EmilGedda/Darkside pull request #3
Opened 2019-03-02 19:29 UTC by Anders-E

2019-03-02 20:22 UTC, EmilGedda requested changes

2019-03-02 20:22 UTC, EmilGedda commented on src/material.ts
> +    }
rename lambda -> waveLength

2019-03-02 21:32 UTC, Anders-E commented on src/material.ts
> +    }
Renaming lambda -> wavelength (apparently a single word)

2019-03-02 22:46 UTC, EmilGedda commented
Rebase pls

2019-03-03 12:25 UTC, EmilGedda approved these changes

2019-03-03 12:25 UTC, merged